# The default build for wasp-os. Modify to customize your own build.
# At least one watch face must be specified. Quick ring apps will be added in order.

[[app]]
file = 'apps/sleep_tk.py'
quick_ring = true

[[app]]
file = 'apps/heart.py'
quick_ring = true


[[watchface]]
file = 'watch_faces/clock.py'

